# Generated by Django 5.0.6 on 2024-12-18 05:22

import django.db.models.deletion
import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='video')),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='admin_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_english', models.CharField(blank=True, max_length=50, null=True)),
                ('author_hindi', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('number', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.IntegerField(blank=True, default=0, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='login_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('mobile_no', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('languages', models.CharField(blank=True, max_length=100, null=True)),
                ('theme', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('password_time', models.DateTimeField(blank=True, null=True)),
                ('membership', models.BooleanField(default=False)),
                ('membership_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_english', models.CharField(max_length=255)),
                ('topic_hindi', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('number', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('languages', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_no', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='u_image')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name_english', models.CharField(blank=True, max_length=255, null=True)),
                ('book_name_hindi', models.CharField(blank=True, max_length=255, null=True)),
                ('book_subtitle_english', models.CharField(blank=True, max_length=255, null=True)),
                ('book_subtitle_hindi', models.CharField(blank=True, max_length=255, null=True)),
                ('book_front_image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('book_details_english', models.TextField(blank=True, null=True)),
                ('book_details_hindi', models.TextField(blank=True, null=True)),
                ('book_price_discount', models.IntegerField()),
                ('book_price', models.FloatField()),
                ('book_keywords', django_mysql.models.ListTextField(models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=100)),
                ('book_file', models.FileField(blank=True, null=True, upload_to='book')),
                ('book_free_demo', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('number', models.IntegerField(blank=True, default=0, null=True)),
                ('purchase', models.BooleanField(default=False)),
                ('purchase_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('draft', models.BooleanField(default=False)),
                ('sutrakar', django_mysql.models.ListTextField(models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=100)),
                ('vyakhyakar', django_mysql.models.ListTextField(models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=100)),
                ('anuvadkarta', django_mysql.models.ListTextField(models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=100)),
                ('author_data', models.ManyToManyField(to='myapp.author')),
                ('language_data', models.ManyToManyField(to='myapp.languages')),
                ('topic_data', models.ManyToManyField(blank=True, null=True, to='myapp.topic')),
            ],
        ),
        migrations.CreateModel(
            name='hylighter1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.TextField(blank=True, default='[]', null=True)),
                ('book_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.books')),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login_user')),
            ],
        ),
        migrations.CreateModel(
            name='download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('book_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.books')),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login_user')),
            ],
        ),
        migrations.CreateModel(
            name='add_to_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('book_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.books')),
                ('user_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.login_user')),
            ],
        ),
        migrations.CreateModel(
            name='show_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_data', models.ManyToManyField(blank=True, null=True, to='myapp.login_user')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='topic_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.topic'),
        ),
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('book_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.books')),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login_user')),
            ],
        ),
    ]
